networks:
  mynetwork:
    external: true
# 服务node
services:
  xxx:
    container_name: xxx
    hostname: xxx
    image: xxx
    networks:
      mynetwork:
        ipv4_address: 192.169.xxx.xxx
    environment:
      - JAVA_HOME=/opt/jdk
      - PATH=/opt/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
      - ../../public/code/jdk-17.0.13+11:/opt/jdk
      - ../../public/script/hosts:/etc/hosts
      - ../../public/download:/data/download
      - ./script:/data/script
    tty: true
    # systemctl 能够正常使用
    privileged: true
    command:
      - /bin/sh
      - -c
      - |
        /usr/sbin/init