networks:
  carm_network:
    external: true
# 服务node
services:
  haproxy:
    container_name: haproxy
    hostname: haproxy
    image: dayello/centos:arm64_7.9.2009
    networks:
      carm_network:
        ipv4_address: 192.170.1.1
    # environment:
    #   - JAVA_HOME=/opt/jdk
    #   - PATH=/opt/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
      - 7100:7100
      - 7200:7200
      - 1936:1936
    volumes:
      - ../../public/script/hosts:/etc/hosts
      - ../../public/download:/data/download
      - ./script:/data/script
      - ./code:/data/code
      - ./conf/haproxy.cfg:/etc/haproxy/haproxy.cfg
    tty: true
    # systemctl 能够正常使用
    privileged: true
    command:
      - /bin/sh
      - -c
      - |
        /usr/sbin/init