networks:
  carm_network:
    external: true
# 服务node
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:7.2.10
    networks:
      carm_network:
        ipv4_address: 192.170.3.1
    # environment:
    #   - JAVA_HOME=/opt/jdk
    #   - PATH=/opt/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
      - 6379:6379
    volumes:
      # - ../../public/code/jdk-17.0.13+11:/opt/jdk
      - ../../public/script/hosts:/etc/hosts
      - ../../public/download:/data/download
      - ./script:/data/script
    tty: true
    # systemctl 能够正常使用
    privileged: true