networks:
  carm_network:
    external: true
# 服务node
services:
  gateway1:
    container_name: gateway1
    hostname: gateway1
    image: dayello/centos:arm64_7.9.2009
    networks:
      carm_network:
        ipv4_address: 192.170.2.1
    environment:
      - JAVA_HOME=/opt/jdk
      - PATH=/opt/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
      - 7101:7100
      - 7201:7200
    volumes:
      - ../../public/code/jdk17.0.13_aarch64:/opt/jdk
      - ../../public/script/hosts:/etc/hosts
      - ../../public/download:/data/download
      - ./script:/data/script
      - ./code/gateway:/opt/gateway
    tty: true
    # systemctl 能够正常使用
    privileged: true
    # java -jar /opt/gateway/jtt808-server-1.0.0-SNAPSHOT.jar org.yzh.web.JT808Application
    command:
      - /bin/sh
      - -c
      - |
        /usr/sbin/init

  gateway2:
    container_name: gateway2
    hostname: gateway2
    image: dayello/centos:arm64_7.9.2009
    networks:
      carm_network:
        ipv4_address: 192.170.2.2
    environment:
      - JAVA_HOME=/opt/jdk
      - PATH=/opt/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
      - 7102:7100
      - 7202:7200
    volumes:
      - ../../public/code/jdk17.0.13_aarch64:/opt/jdk
      - ../../public/script/hosts:/etc/hosts
      - ../../public/download:/data/download
      - ./script:/data/script
      - ./code/gateway:/opt/gateway
    tty: true
    # systemctl 能够正常使用
    privileged: true
    # java -jar /opt/gateway/jtt808-server-1.0.0-SNAPSHOT.jar org.yzh.web.JT808Application
    command:
      - /bin/sh
      - -c
      - |
        /usr/sbin/init